[package]
name = "bandsnatch"
version = "0.1.0"
edition = "2021"
description = "A CLI batch downloader for your Bandcamp collection"
authors = ["Michael Mitchell <michael@ovyerus.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Ovyerus/bandsnatch"
repository = "https://github.com/Ovyerus/bandsnatch"
keywords = ["cli", "bandcamp", "music", "downloader", "bcdl"]
categories = ["command-line-utilities", "multimedia::audio"]
default-run = "bs"

# TODO: create a shared `src/lib.rs` and then the named binaries in `src/bin`
# with same contents instead
# (https://github.com/rust-lang/cargo/issues/5930#issuecomment-449331569)
# Or is there a better way for bin aliases?
[[bin]]
name = "bs"
path = "src/main.rs"

[[bin]]
name = "bandsnatch"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "3.2", features = ["derive", "env", "unicode"] }
env_logger = "0.9"
futures = "0.3.24"
futures-util = { version = "0.3", features = ["io"] }
indicatif = "0.17"
log = "0.4"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde-aux = "4"
serde_json = "1"
shellexpand = "2.1.2"
simple-error = "0.2"
soup = "0.5"
tokio = { version = "1", features = ["full"] }
tokio-scoped = "0.2.0"
zip = "0.6"
