[package]
name = "bcdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
indicatif = "0.17"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
"serde-aux" = "4"
serde_json = "1"
"simple-error" = "0.2"
soup = "0.5"
surf = { version = "2.3", features = ["h1-client", "middleware-logger"] }
tokio = { version = "1", features = ["full"] }