[package]
name = "bcdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "3.2", features = ["derive"] }
"futures-util" = { version = "0.3", features = ["io"] }
indicatif = "0.17"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
"serde-aux" = "4"
serde_json = "1"
"simple-error" = "0.2"
soup = "0.5"
tokio = { version = "1", features = ["full"] }
zip = "0.6"